### ISSUE TITLE
Install module

### ISSUE THREAD

**Issue by Martinvdm** [DanielDent/docker-nginx-ssl-proxy#10]
Hi,

Your docker is working perfect. But Exchange 2016 Outlook Anywhere is not working. It seems that 
more_set_input_headers is missing and can be installed with nginx-extras module. But how can i accomplish this with the Docker Compose?

Thanks

Martin

**Comment by DanielDent** [comment]
This is probably best handled by creating another image that uses this image in a FROM directive as a base. Then apt-get + changes to proxy configuration.
