### ISSUE TITLE
Option to Change Challenge Port

### ISSUE THREAD

**Issue by pogzie** [DanielDent/docker-nginx-ssl-proxy#16]
Is it possible to set an environment variable for a desired port for the ACME http challenge?

Im somewhat having issues with a failing challenge due to the redirects im using because my port 80 is already used. 

https://github.com/certbot/certbot/issues/5616

**Comment by DanielDent** [comment]
As that issue states, Let's Encrypt only supports validation over port 80. If that's a no-go for you, you'll need to use their DNS validation methods, which is not currently supported by this image.
