### ISSUE TITLE
Question About Renewal

### ISSUE THREAD

**Issue by calebbrewer** [DanielDent/docker-nginx-ssl-proxy#2]
I just started using this and it's great. Thanks for putting it together.

Just a quick question... I can't find the part of your coded that handles the auto renewal that you talk about in the readme. Where is it at? I'm sure I'm just missing something.

This is my first time messing with SSL and letsencrypt so please forgive me if this was a dumb question.

**Comment by DanielDent** [comment]
Hi Caleb,

Glad you find this useful.

Auto-renewal is handled by certbot, e.g. https://github.com/DanielDent/docker-nginx-ssl-proxy/blob/f15d324885ef97767d0596ee5719fcd91dfbc1d5/services.d/certbot/run

S6 overlay is used to run everything in the services.d folder.

Hope this helps, please re-open if you have further questions.

**Comment by calebbrewer** [comment]
Ahh... Thank you. I will have to look into s6.
