### ISSUE TITLE
How set proxy_set_header?

### ISSUE THREAD

**Issue by sgehrman** [DanielDent/docker-nginx-ssl-proxy#22]
Sorry for the noob question. I'm having problems and I was told I need:

    proxy_set_header  X-Forwarded-Proto $scheme;

Where and how do I set this?

I see it is set in the default.conf, but something is wrong. Is X-Forwarded-Proto deprecated?  Is there a better way now?  https://support.cocoatech.com is the site I'm trying to fix.  My css files aren't loading because they are referenced with http://.  I was told that I need X-Forwarded-Proto to make that work.

Thanks

**Comment by DanielDent** [comment]
You'll probably want to update your CSS references. `X-Forwarded-Proto` is always set by this container automatically, there is nothing you need to do for that header to be present.

**Comment by sgehrman** [comment]
I can't do that as it's controlled by another site.  tenderapp.com
That site is http, but I added this proxy to get it to work at https.  Their support guy said I need this forward-proto.  I see it's there, but not sure why it's not working.

I don't see X-Forwarded-Proto in the reponse header. Should it be there?

**Comment by sgehrman** [comment]
The guy at tender helped me fix it.

Changed 3 things in the default.conf

1) add 443:    server cocoatech.tenderapp.com:443; 
2) removed:   proxy_set_header X-Forwarded-Proto $scheme; 
3) https, not http on:   proxy_pass https://origin;
